# Generated by Django 4.1 on 2022-09-02 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('y', 'yandex'), ('o', 'ozon')], max_length=1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('publish_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewTags',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newtags', to='news.new')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('news', models.ManyToManyField(through='news.NewTags', to='news.new')),
            ],
        ),
        migrations.AddField(
            model_name='newtags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newtags', to='news.tag'),
        ),
        migrations.AddField(
            model_name='new',
            name='tags',
            field=models.ManyToManyField(through='news.NewTags', to='news.tag'),
        ),
    ]
